return {
        {
                'https://github.com/LmanTW/themify.nvim',
                -- lazy = false,
                priority = 999,
                cmd = 'Themify',
                keys = { { '<leader>tc', '<cmd>Themify<cr>', mode = 'n', desc = 'themify' } },
                config = function()
                        require('themify').setup({
                                -- with toggle dark/light variants
                                -- { 'https://github.com/mcchrish/zenbones.nvim.git',                      dependencies = { 'https://github.com/rktjmp/lush.nvim.git' }, },
                                { 'https://github.com/nuvic/flexoki-nvim', },
                                { 'https://github.com/nyoom-engineering/oxocarbon.nvim.git', },
                                { 'https://github.com/mellow-theme/mellow.nvim', },
                                { 'https://github.com/folke/tokyonight.nvim.git', },
                                { 'https://github.com/NLKNguyen/papercolor-theme.git', },
                                { 'https://github.com/cormacrelf/vim-colors-github.git', },
                                { 'https://github.com/navarasu/onedark.nvim.git', },
                                { 'https://github.com/olimorris/onedarkpro.nvim.git', },
                                { 'https://github.com/sonph/onehalf.git', },
                                { 'https://github.com/preservim/vim-colors-pencil.git', },
                                { 'https://github.com/rakr/vim-one.git', },
                                { 'https://github.com/rakr/vim-two-firewatch.git', },
                                { 'https://github.com/Mofiqul/vscode.nvim.git', },
                                { 'https://github.com/catppuccin/nvim.git', },
                                { 'https://github.com/ishan9299/nvim-solarized-lua.git', },
                                { 'https://github.com/lourenci/github-colors.git', },
                                { 'https://github.com/miikanissi/modus-themes.nvim.git', },
                                { 'https://github.com/polirritmico/monokai-nightasty.nvim.git', },
                                { 'https://github.com/ramojus/mellifluous.nvim.git', },
                                { 'https://github.com/rebelot/kanagawa.nvim.git', },
                                { 'https://github.com/rmehri01/onenord.nvim.git', },
                                { 'https://github.com/sainnhe/edge.git', },
                                { 'https://github.com/sainnhe/everforest', },
                                { 'https://github.com/savq/melange-nvim.git', },
                                { 'https://github.com/kdheepak/monochrome.nvim.git', },
                                { 'https://github.com/craftzdog/solarized-osaka.nvim.git', },
                                -- without toggle dark/light schemes support
                                { 'https://github.com/noorwachid/nvim-nightsky.git', },
                                { 'https://github.com/olivercederborg/poimandres.nvim.git', },
                                { 'https://github.com/CrispyBaccoon/evergarden.git', },
                                { 'https://github.com/HoNamDuong/hybrid.nvim.git', },
                                { 'https://github.com/scottmckendry/cyberdream.nvim.git', },
                                { 'https://github.com/EdenEast/nightfox.nvim.git', },
                                { 'https://github.com/Mofiqul/dracula.nvim.git', },
                                { 'https://github.com/PHSix/nvim-hybrid.git', },
                                { 'https://github.com/Tsuzat/NeoSolarized.nvim.git', },
                                { 'https://github.com/Verf/deepwhite.nvim.git', },
                                -- { 'https://github.com/adisen99/codeschool.nvim.git', },
                                { 'https://github.com/alexmozaidze/palenight.nvim.git', },
                                { 'https://github.com/andersevenrud/nordic.nvim.git', },
                                { 'https://github.com/bluz71/vim-moonfly-colors.git', },
                                { 'https://github.com/bluz71/vim-nightfly-colors.git', },
                                { 'https://github.com/cryptomilk/nightcity.nvim.git', },
                                { 'https://github.com/dasupradyumna/midnight.nvim.git', },
                                { 'https://github.com/ellisonleao/gruvbox.nvim.git', },
                                { 'https://github.com/hoprr/calvera-dark.nvim.git', },
                                { 'https://github.com/judaew/ronny.nvim.git', },
                                { 'https://github.com/kvrohit/rasmus.nvim.git', },
                                { 'https://github.com/kvrohit/substrata.nvim.git', },
                                { 'https://github.com/kyazdani42/blue-moon.git', },
                                { 'https://github.com/marko-cerovac/material.nvim.git', },
                                { 'https://github.com/nvimdev/zephyr-nvim.git', },
                                { 'https://github.com/ofirgall/ofirkai.nvim.git', },
                                { 'https://github.com/oxfist/night-owl.nvim.git', },
                                { 'https://github.com/rafamadriz/neon.git', },
                                { 'https://github.com/rockerBOO/boo-colorscheme-nvim.git', },
                                { 'https://github.com/sainnhe/sonokai.git', },
                                -- { 'https://github.com/shaunsingh/moonlight.nvim.git', },
                                { 'https://github.com/shaunsingh/nord.nvim.git', },
                                -- { 'https://github.com/svrana/neosolarized.nvim.git', },
                                { 'https://github.com/titanzero/zephyrium.git', },
                                -- { 'https://github.com/tjdevries/gruvbuddy.nvim.git', },
                                { 'https://github.com/tomasiser/vim-code-dark.git', },
                                { 'https://github.com/xero/miasma.nvim.git', },
                                { 'https://github.com/zootedb0t/citruszest.nvim.git', },
                                { 'https://github.com/ChristianChiarulli/nvcode-color-schemes.vim.git', },
                                { 'https://github.com/rafi/awesome-vim-colorschemes.git', },
                        })
                end,
        }
}
