if not vim.g.color_name then
	vim.g.color_name = 'kanagawa'
end
return {
	-- with toggle dark/light variants
	{ 'https://github.com/Mofiqul/vscode.nvim', lazy = true },
	{ 'https://github.com/catppuccin/nvim', lazy = true },
	{ 'https://github.com/folke/tokyonight.nvim', lazy = true },
	{ 'https://github.com/ishan9299/nvim-solarized-lua', lazy = true },
	{ 'https://github.com/lourenci/github-colors', lazy = true },
	{ 'https://github.com/miikanissi/modus-themes.nvim', lazy = true },
	{ 'https://github.com/polirritmico/monokai-nightasty.nvim', lazy = true },
	{ 'https://github.com/ramojus/mellifluous.nvim', lazy = true },
	{ 'https://github.com/rebelot/kanagawa.nvim', lazy = true },
	{ 'https://github.com/rmehri01/onenord.nvim', lazy = true },
	{ 'https://github.com/sainnhe/edge', lazy = true },
	{ 'https://github.com/sainnhe/everforest', lazy = true },
	{ 'https://github.com/savq/melange-nvim', lazy = true },
	{ 'https://github.com/kdheepak/monochrome.nvim', lazy = true },
	{ 'https://github.com/nyoom-engineering/oxocarbon.nvim', lazy = true },
	{ 'https://github.com/craftzdog/solarized-osaka.nvim', lazy = true },
	-- -- without toggle dark/light schemes support
	-- { 'https://github.com/scottmckendry/cyberdream.nvim', lazy = true },
	-- { 'https://github.com/ChristianChiarulli/nvcode-color-schemes.vim', lazy = true },
	-- { 'https://github.com/EdenEast/nightfox.nvim', lazy = true },
	-- { 'https://github.com/Mofiqul/dracula.nvim', lazy = true },
	-- { 'https://github.com/PHSix/nvim-hybrid', lazy = true },
	-- { 'https://github.com/Tsuzat/NeoSolarized.nvim', lazy = true },
	-- { 'https://github.com/Verf/deepwhite.nvim', lazy = true },
	-- { 'https://github.com/adisen99/codeschool.nvim', lazy = true },
	-- { 'https://github.com/alexmozaidze/palenight.nvim', lazy = true },
	-- { 'https://github.com/andersevenrud/nordic.nvim', lazy = true },
	-- { 'https://github.com/bluz71/vim-moonfly-colors', lazy = true },
	-- { 'https://github.com/bluz71/vim-nightfly-colors', lazy = true },
	-- { 'https://github.com/cryptomilk/nightcity.nvim', lazy = true },
	-- { 'https://github.com/dasupradyumna/midnight.nvim', lazy = true },
	-- { 'https://github.com/ellisonleao/gruvbox.nvim', lazy = true },
	-- { 'https://github.com/hoprr/calvera-dark.nvim', lazy = true },
	-- { 'https://github.com/judaew/ronny.nvim', lazy = true },
	-- { 'https://github.com/kvrohit/rasmus.nvim', lazy = true },
	-- { 'https://github.com/kvrohit/substrata.nvim', lazy = true },
	-- { 'https://github.com/kyazdani42/blue-moon', lazy = true },
	-- { 'https://github.com/marko-cerovac/material.nvim', lazy = true },
	-- { 'https://github.com/navarasu/onedark.nvim', lazy = true },
	-- { 'https://github.com/nvimdev/zephyr-nvim', lazy = true },
	-- { 'https://github.com/ofirgall/ofirkai.nvim', lazy = true },
	-- { 'https://github.com/olivercederborg/poimandres.nvim', lazy = true },
	-- { 'https://github.com/oxfist/night-owl.nvim', lazy = true },
	-- { 'https://github.com/rafamadriz/neon', lazy = true },
	-- { 'https://github.com/rafi/awesome-vim-colorschemes', lazy = true },
	-- { 'https://github.com/rockerBOO/boo-colorscheme-nvim', lazy = true },
	-- { 'https://github.com/sainnhe/sonokai', lazy = true },
	-- { 'https://github.com/shaunsingh/moonlight.nvim', lazy = true },
	-- { 'https://github.com/shaunsingh/nord.nvim', lazy = true },
	-- { 'https://github.com/svrana/neosolarized.nvim', lazy = true },
	-- { 'https://github.com/titanzero/zephyrium', lazy = true },
	-- { 'https://github.com/tjdevries/gruvbuddy.nvim', lazy = true },
	-- { 'https://github.com/tomasiser/vim-code-dark', lazy = true },
	-- { 'https://github.com/xero/miasma.nvim', lazy = true },
	-- { 'https://github.com/zootedb0t/citruszest.nvim', lazy = true },
}
