return {
  -- with toggle dark/light variants
  {
    'https://github.com/mcchrish/zenbones.nvim.git',
    lazy = true,
    optional = true,
    dependencies = { 'https://github.com/rktjmp/lush.nvim.git' },
  },
  { 'https://github.com/nyoom-engineering/oxocarbon.nvim.git',            lazy = true },
  { 'https://github.com/mellow-theme/mellow.nvim',                        lazy = true, optional = true },
  { 'https://github.com/folke/tokyonight.nvim.git',                       lazy = true, optional = true },
  { 'https://github.com/NLKNguyen/papercolor-theme.git',                  lazy = true, optional = true },
  { 'https://github.com/cormacrelf/vim-colors-github.git',                lazy = true, optional = true },
  { 'https://github.com/navarasu/onedark.nvim.git',                       lazy = true, optional = true },
  { 'https://github.com/olimorris/onedarkpro.nvim.git',                   lazy = true, optional = true },
  { 'https://github.com/sonph/onehalf.git',                               lazy = true, optional = true },
  { 'https://github.com/preservim/vim-colors-pencil.git',                 lazy = true, optional = true },
  { 'https://github.com/rakr/vim-one.git',                                lazy = true, optional = true },
  { 'https://github.com/rakr/vim-two-firewatch.git',                      lazy = true, optional = true },
  { 'https://github.com/Mofiqul/vscode.nvim.git',                         lazy = true, optional = true },
  { 'https://github.com/catppuccin/nvim.git',                             lazy = true, optional = true },
  { 'https://github.com/ishan9299/nvim-solarized-lua.git',                lazy = true, optional = true },
  { 'https://github.com/lourenci/github-colors.git',                      lazy = true, optional = true },
  { 'https://github.com/miikanissi/modus-themes.nvim.git',                lazy = true, optional = true },
  { 'https://github.com/polirritmico/monokai-nightasty.nvim.git',         lazy = true, optional = true },
  { 'https://github.com/ramojus/mellifluous.nvim.git',                    lazy = true, optional = true },
  { 'https://github.com/rebelot/kanagawa.nvim.git',                       lazy = true, optional = true },
  { 'https://github.com/rmehri01/onenord.nvim.git',                       lazy = true, optional = true },
  { 'https://github.com/sainnhe/edge.git',                                lazy = true, optional = true },
  { 'https://github.com/sainnhe/everforest',                              lazy = true, optional = true },
  { 'https://github.com/savq/melange-nvim.git',                           lazy = true, optional = true },
  { 'https://github.com/kdheepak/monochrome.nvim.git',                    lazy = true, optional = true },
  { 'https://github.com/craftzdog/solarized-osaka.nvim.git',              lazy = true, optional = true },
  -- -- without toggle dark/light schemes support
  { 'https://github.com/noorwachid/nvim-nightsky.git',                    lazy = true, optional = true },
  { 'https://github.com/olivercederborg/poimandres.nvim.git',             lazy = true, optional = true },
  { 'https://github.com/CrispyBaccoon/evergarden.git',                    lazy = true, optional = true },
  { 'https://github.com/HoNamDuong/hybrid.nvim.git',                      lazy = true, optional = true },
  { 'https://github.com/scottmckendry/cyberdream.nvim.git',               lazy = true, optional = true },
  { 'https://github.com/EdenEast/nightfox.nvim.git',                      lazy = true, optional = true },
  { 'https://github.com/Mofiqul/dracula.nvim.git',                        lazy = true, optional = true },
  { 'https://github.com/PHSix/nvim-hybrid.git',                           lazy = true, optional = true },
  { 'https://github.com/Tsuzat/NeoSolarized.nvim.git',                    lazy = true, optional = true },
  { 'https://github.com/Verf/deepwhite.nvim.git',                         lazy = true, optional = true },
  { 'https://github.com/adisen99/codeschool.nvim.git',                    lazy = true, optional = true },
  { 'https://github.com/alexmozaidze/palenight.nvim.git',                 lazy = true, optional = true },
  { 'https://github.com/andersevenrud/nordic.nvim.git',                   lazy = true, optional = true },
  { 'https://github.com/bluz71/vim-moonfly-colors.git',                   lazy = true, optional = true },
  { 'https://github.com/bluz71/vim-nightfly-colors.git',                  lazy = true, optional = true },
  { 'https://github.com/cryptomilk/nightcity.nvim.git',                   lazy = true, optional = true },
  { 'https://github.com/dasupradyumna/midnight.nvim.git',                 lazy = true, optional = true },
  { 'https://github.com/ellisonleao/gruvbox.nvim.git',                    lazy = true, optional = true },
  { 'https://github.com/hoprr/calvera-dark.nvim.git',                     lazy = true, optional = true },
  { 'https://github.com/judaew/ronny.nvim.git',                           lazy = true, optional = true },
  { 'https://github.com/kvrohit/rasmus.nvim.git',                         lazy = true, optional = true },
  { 'https://github.com/kvrohit/substrata.nvim.git',                      lazy = true, optional = true },
  { 'https://github.com/kyazdani42/blue-moon.git',                        lazy = true, optional = true },
  { 'https://github.com/marko-cerovac/material.nvim.git',                 lazy = true, optional = true },
  { 'https://github.com/navarasu/onedark.nvim.git',                       lazy = true, optional = true },
  { 'https://github.com/nvimdev/zephyr-nvim.git',                         lazy = true, optional = true },
  { 'https://github.com/ofirgall/ofirkai.nvim.git',                       lazy = true, optional = true },
  { 'https://github.com/olivercederborg/poimandres.nvim.git',             lazy = true, optional = true },
  { 'https://github.com/oxfist/night-owl.nvim.git',                       lazy = true, optional = true },
  { 'https://github.com/rafamadriz/neon.git',                             lazy = true, optional = true },
  { 'https://github.com/rockerBOO/boo-colorscheme-nvim.git',              lazy = true, optional = true },
  { 'https://github.com/sainnhe/sonokai.git',                             lazy = true, optional = true },
  { 'https://github.com/shaunsingh/moonlight.nvim.git',                   lazy = true, optional = true },
  { 'https://github.com/shaunsingh/nord.nvim.git',                        lazy = true, optional = true },
  { 'https://github.com/svrana/neosolarized.nvim.git',                    lazy = true, optional = true },
  { 'https://github.com/titanzero/zephyrium.git',                         lazy = true, optional = true },
  { 'https://github.com/tjdevries/gruvbuddy.nvim.git',                    lazy = true, optional = true },
  { 'https://github.com/tomasiser/vim-code-dark.git',                     lazy = true, optional = true },
  { 'https://github.com/xero/miasma.nvim.git',                            lazy = true, optional = true },
  { 'https://github.com/zootedb0t/citruszest.nvim.git',                   lazy = true, optional = true },
  { 'https://github.com/ChristianChiarulli/nvcode-color-schemes.vim.git', lazy = true, optional = true },
  { 'https://github.com/rafi/awesome-vim-colorschemes.git',               lazy = true, optional = true },
}
